//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxInAsp.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Contact
    {

        public int ContactID { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "Required")]
        public string FirstName { get; set; }
        public string Surname { get; set; }

        [DisplayName("Tel No 1")]
        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Invalid Format")]
        public string ContactNo { get; set; }

        [DisplayName("Tel No 2")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Invalid Format")]
        public string AlternateContactNo { get; set; }

        [DisplayName("Image")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public Contact()
        {
            ImagePath = "~/AppFiles/Images/default.png";
        }


    }
}
